.github/workflows/build-n-test.yaml
The CI builds & test library.
The CI should be triggered when:
* commit is pushed to `master` branch
* PR is issued against one of `master`, `development` or user-specific (starting with `@<username>/` branches.
Fixes #19
=> chore: add basic CI

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/missing-feature.md
According to [GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#issue-templates) this YAML header is required for issue templates to be valid. Forgot about it earlier.
=> fix: add YAML front matters for issue templates

.gitignore, src/examples.rs, src/ga.rs, src/ga/builder.rs, src/ga/example.rs, src/ga/individual.rs, src/ga/operators.rs, src/ga/operators/crossover.rs, src/ga/operators/mutation.rs, src/ga/operators/selection.rs, src/ga/probe/json_probe.rs, src/main.rs
This PR cleans up GA implementation and adds basic genetic operators.
* Cleaned up & restructured GA code so from now on it is possible to exchange operator implementations.
* Fixed `ga::Builder`
* Added some basic genetic operators:
* Single point crossover
* Roulette wheel selection
* Stub mutation (waiting for bitstring individual representation)
This PR pushes #21, however it is not there yet.
=> feat: reimplement GA & add some basic genetic operators

src/ga/operators/selection.rs
Adding missing selection operator.
Resolves #36 
I left them below in form of a review.
=> feat: add random selection operator

src/ga/operators/selection.rs
Should be merged only after
* #69 
is merged.
Added missing selection operator. 
This is one of two popular implementations. Second one has additional `r` parameter, which is used to decide which of random selected individuals to use as a parent. I left the second implementation behind for now, as presence of additional parameter raises some problems with our current approach to operator implementations. Namely we can't just add additional param to function declaration as it would break existing selection operator API in GA implementation (how do we decide whether to pass 2 or 3 params to operator in runtime?). One possible solution might be to implement operators as traits (concrete implementations as structs with `FnMut` trait implemented). Such approach would not only allow for …
=> feat: add first type of rank selection 

src/ga/operators/selection.rs
Should be merged only after 
* #71 
is merged.
Added tournament selection operator. 
Due to restrictions coming from construction of our API, it cannot be parameterized. However this is to be changed when idea mentioned in description of #71 is implemented.
Resolves #38
=> feat: add tournament selection operator

src/ga/operators/selection.rs
Should be merged only after
* #72 
is merged.
Added SUS selection operator for GA. 
Closes #40
This implementation allows for multiple addition of single individual to the selected pool in case it spans over multiple pointer positions.
=> feat: add stochastic universal sampling selection operator

src/examples.rs, src/ga.rs, src/ga/builder.rs, src/ga/operators/crossover.rs, src/ga/operators/mutation.rs, src/ga/operators/selection.rs
Should be merged only after
* #74 
is merged.
So following up on [this comment](https://github.com/kkafar/evolutionary-algorithms/pull/71#issue-1445261313) I enclosed GA operators inside traits. Such approach allows for:
* Parameterization of operators
* Implementation overloading for different chromosome types
* Potentially having some internal mutable state inside operator
I've tried to use `Fn` / `FnMut` / `FnOnce` traits, but Rust [docs state that implementing it for custom structs is considered unstable](https://doc.rust-lang.org/stable/std/ops/trait.FnMut.html#required-methods), thus I went with `apply` method convention (inspired by Scala).
N/A
I did not use any of `Fn*` traits, because it is reported that [implementing it for custom structs is …
=> refact: implement GA operators as traits

src/ga/operators/selection.rs
Add rank with param selection operator.
Resolves #70 
Followed algorithm description placed in "Introduction to Genetic Algorithms" by S. N. Sivanandam & S. N. Deepa.
=> feat: add rank with param selection operator 

src/ga/operators/selection.rs
Add `size_factor: f64` parameter, so that it can be determined what part of population should take part in each tournament for selecting individual.
Resolves #82
=> feat: parameterize tournament selection operator

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/missing-feature.md, .github/PULL_REQUEST_TEMPLATE.md
I didn't like headers I previously add. Templates are more lean now.
Also added comments explaining when to add issue / PR to a project and when not to.
=> chore: simplify issue templates

src/ga.rs
Mutation operator is now being called for every child coming from crossover operator.
Resolves #95 
I was not sure whether to apply mutation on:
* current generation + new children
* whole generation after replacement
* just new children
Ultimately I went with last option: children are mutated and then replacement operator happens.
=> fix: apply mutation on children

example/src/ga.rs, src/ga.rs, src/ga/builder.rs
Move `mutation_rate` param from `GAConfig` to mutation operator configuration.
Resolves #130
=> feat: parameterize mutation operators with `mutation_rate`

example/src/ga.rs, src/ga.rs, src/ga/builder.rs, src/ga/individual.rs, src/ga/population.rs
* Added population module with two simple populations generators:
* `RandomPoints`
* `BitStrings` 
* Modified GA's builder interface to work with these.
* Updated implementation of GA
Resolves #131 
Resolves #139 
Resolves #140
=> [GA] Population initialization

example/src/ga/rastrigin.rs, example/src/ga/sum_of_squares.rs, src/ga.rs, src/ga/builder.rs, src/ga/individual.rs, src/ga/operators/crossover.rs, src/ga/operators/mutation.rs, src/ga/operators/selection.rs, src/ga/population.rs, src/ga/probe.rs, src/ga/probe/stdout_probe.rs
Removed `ChromosomeWrapper` type && fixed all issues that arised.
Basically this is a regression, as right now you can not add custom state to your individual, but it was stated as project requirement.
Advantage of this change is that the code got much simpler. 
Resolves #132
=> chore!: remove `ChromosomeWrapper`

example/src/ga.rs, src/ga/population.rs, tests/selection_tests.rs
Allow for implicit constraints on point domain in `RandomPoints` population generator.
I decided to detect whether there are constraints or not by checking whether constraints vector is empty. I did not use `Option` because using `.unwrap()` consumes `self` & it lead to inconveniences.
=> feat: allow for implicit constraints on point domain in `RandomPoints`

example/src/ga.rs, example/src/ga/wordmax.rs, example/src/main.rs, src/ga/builder.rs, src/ga/builder/presets.rs, src/ga/probe.rs, src/ga/probe/empty.rs, src/ga/probe/stdout_probe.rs
Add better defaults for builder.
Right now this PR is stuck, due to problems with implementation.
Rust lacks few important language mechanisms:
* Trait specialization (same as C++ template spec.) is in early development process:
* https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md
* https://github.com/rust-lang/rust/issues/31844
* Negative impls are unstable
* https://github.com/rust-lang/rust/issues/68318
* https://doc.rust-lang.org/beta/unstable-book/language-features/negative-impls.html
It is an issue, because:
1. We want to provide a blanket implementation over `T: Chromosome` for `Builder` struct. It would be ridiculous to force user to implement custom `Builder`.
2. Different operators require different trait bounds on `Chromosome`, thus defaults for …
=> feat: better defaults for GA builder

example/src/ga.rs, example/src/ga/rastrigin.rs, example/src/ga/wordmax.rs, example/src/main.rs, src/ga.rs, src/ga/builder.rs, src/ga/builder/presets.rs, src/ga/individual.rs
Resolves #178 
* Blanket implementation of `Deref` trait for `Individual`
* Made fitness functions to operate on chromosome instead of individual
=> fix: make GA compliant to test function interface

example/src/ga.rs, example/src/main.rs, src/ga.rs, src/ga/builder/bistring.rs, src/ga/builder/realvalued.rs, src/ga/operators/selection.rs, src/ga/probe.rs, src/ga/probe/aggregated_probe.rs, src/ga/probe/policy_driven_probe.rs, src/ga/probe/probing_policy.rs, src/ga/probe/stdout_probe.rs, tests/builder.rs, tests/selection_tests.rs
This PR extends probing mechanisms in GA and solutions introduced here should also be taken into consideration while implementing / extending logging mechanisms for other algorithms. 
* Added `ProbingPolicy` trait
* Added `GenerationInterval` probing policy
* Added `ElapsedTime` probing policy
* Added new `PolicyDrivenProbe` - this probe can be passed a `ProbingPolicy` and it will log only when given policy allows it to
* Changed the way probing are exported out of `crate::ga::probe` module - now they are exported directly, not via their designated module. That means old import: 
```rust
use ecrs::ga::probe::stdout_probe::StdoutProbe
```
now becomes
```rust
use ecrs::ga::probe::StdoutProbe
```
* Added Aggregated probe, which can be passed a vector of probes and executes them sequentially. …
=> feat: add probing policy

src/ga/operators/crossover.rs, tests/crossover_tests.rs
=> feat: PPX crossover operator

src/ga/population.rs
Added random permutation population generator
Closes #148 
Generator doesn't promises uniquids of generated individuals, it is possible to implement but it will generate a lot of overhead
=> feat: random permutation population generator

examples/ga_ackley_test_function.rs, src/ga.rs, src/ga/builder.rs, src/ga/builder/bistring.rs, src/ga/builder/generic.rs, src/ga/builder/realvalued.rs, src/ga/operators.rs, src/ga/operators/fitness.rs, src/lib.rs
=> feat: change fitness from function to struct

src/ga.rs, src/ga/builder/bistring.rs, src/ga/builder/realvalued.rs, src/ga/operators/replacement.rs
So I've just merged #263 skipping review process 🤦🏻‍♂️  and had to immediately introduce some fixes;
1. I decided to take ownership of population & children, so that I can modify it in the operator and avoid necessity of creating a copy.
2. Added `requires_children_fitness` method which indicated whether children's fitness should be evaluated.
3. Fixed `BothParents` implementation
=> feat: `replacement` - improve interface & some fixes

src/ff.rs, src/ff/auxiliary.rs
Fix for out-of-bound search in FF
Resolves #289
=> [FF] Bugfix attempt

src/ff.rs
Makes FFCfg fields public
##Linked issues
Resolves #296
=> Make FireflyAlgorithmCfg public

src/ff.rs
User can now provide a struct implementing rand::Distribution<X>, which gets utilized in calculating flight distance of a firefly
Resolves #295 
For *now* rand::Distribution<X> is acutally Distribution<f64>. 
While generally advisable to not use "top-'' or ''bottom-heavy'' distributions, it's not actually dissuaded.
=> Ff refactor

examples/ff.rs, examples/ff_logging.rs, src/ff.rs
Introducing more consistent naming with other algorithms.
Resolves #305
=> refact(FF): rename `execute` -> `run`

coco/src/main.rs, src/lib.rs, src/prelude.rs
I did not want to re-export more submodules as their names are identical e.g. ga::probe, pso::probe... 
Maybe we should consider doing some refactoring. 
Resolves #330
=> feat: add basic prelude module

src/ga/operators/crossover.rs
Added implementation of `UniformParameterized` crossover operator. 
It is now possible to specify the bias for rng when generating bitmask.
=> feat(GA): implement `UniformParameterized` crossover operator

coco/src/adapter.rs, examples/ga.rs, src/ga.rs, src/ga/builder.rs, src/ga/builder/bitstring.rs, src/ga/builder/generic.rs, src/ga/builder/realvalued.rs, src/ga/operators/fitness.rs, tests/builder_tests.rs
So that it is possible to evalutate fitness for more complex problems, that require additional state stored in individual instance.
=> feat: parameterize fitness with IndividualT

src/ga/population.rs, src/ga/population/tools.rs
Added `population::tools` module for primitive chromosome generation (currently only random points)
Resolves #371
Resolves #370
=> feat: add population::tools module with methods for primitive chromosome generation

src/ga.rs
=> fix: set duration before first on_new_best call

examples/jssp/problem/individual.rs, src/ga.rs, src/ga/probe/stdout_probe.rs
Currently there are few places in the code that try to achieve contradictory optimization targets: some operators treat "lesser" individuals as better, some treat "greater" ones as better.
This PR aims to clean things up and target only minimization ("lesser" individuals are "better").
Maximization can be achieved by implementing custom individual type with custom `Ord` trait implementation.
TODO: Implement MinIndividual & MaxIndividual types in the ecrs library, so both types of optimalization are available for user out of the box.
=> fix: inconsistences in individual comparison

examples/jssp/problem.rs, examples/jssp/problem/population.rs
`Machine::new` method had redundant parameter.
Resolves #390
=> fix(jssp): remove redundant param in  func

examples/jssp/main.rs, examples/jssp/parse.rs, examples/jssp/problem.rs, examples/jssp/problem/population.rs
1. Refactored `JsspPopProvider` so that it is now created from `JsspInstance` and not from file path. 
2. Implemented `TryFrom<PathBuf>` for `JsspPopProvider` so that loading directly from path file is still possible.
3. Moved all `JsspInstance` adapting logic from `generate` method to `new` method so that repeated generation is much cheaper.
4. Added simple mechanism to infer population size for the solver automaticaly for the given problem instance (due to rules described in the paper).
Closes #389
=> feat(jssp): refact `JsspPopProvider` & infer population size for given instance automaticaly

.github/workflows/add-issue-to-project.yaml
Added basic workflow to automatize addition of new issues to the project.
It is possible that it won't work, because I did not pass `github-token`
param, but we'll see.
Closes #377
=> feat(ci): workflow for auto-adding issues to the project

src/ga/probe/aggregated_probe.rs
Such method simplifies creation of `AggregatedProbe`
Closes #408
Currently each element in the passed array must be of the `Box` type.
=> feat(ga): implement `with_probes` for `AggregatedProbe`

src/ga/operators/crossover.rs, src/ga/operators/mutation.rs, src/ga/operators/selection.rs
Make `ThreadRng` default RNG type for all GA operators.
Closes #362
=> feat(ga): make `ThreadRng` default generator type for all GA operators

examples/jssp/logging.rs
For the time being it makes testing ECDataKit much easier and handy.
=> fix(jssp): truncate log files instead of appending

examples/jssp/problem/probe.rs
ECDataKit proceses csv files using `polars` library. It seems that `pl.DataFrame.read_csv` deduces number of columns from the first record read and then if it encouters longer record (with more columns)
it ignores additional values.
I could handle it solely on ECDataKit side by reading the whole data file, prepending it with such marker record and then overwriting it, but doing it via ecrs seems easier for now.
=> fix(ecdatakit): print marker record describing max num. of columns

examples/jssp/problem/probe.rs
When strings were specifed polars infered `str` as data type for each column.
=> fix(ecdatakit): print empty values in marker line

examples/jssp/cli.rs, examples/jssp/logging.rs, examples/jssp/main.rs, examples/jssp/problem/probe.rs, examples/jssp/util.rs
Multiple output files are now produced. Description can be found in ECDK docs.
=> refact(jssp): store all run output in single directory instead of single file

Cargo.toml, examples/jssp/problem/individual.rs
=> chore: add debug symbols to release build & some comments

examples/jssp/main.rs, examples/jssp/problem.rs, examples/jssp/problem/population.rs
Operation zero is now inserted to the begining of the predecessor list.
I've not found any other places in codebase where predecessors are modified ==> the order should be guaranteed.
The order is ascending.
This will allow for few planned preformance optimizations
=> feat(jssp): guarantee operation predecessors order

examples/jssp/problem/fitness.rs
Runtime improvement.
We do not need to iterate over all predecessors finish times as:
1. the predecessor order is guaranteed since #444 
2. it is enough to check finish time of direct predecessor as it could not have been scheduled before all its predecessors had been finished, thus its finish time >= (= when duration == 0) any other predecessor's finish time.
I've also tested this solution with assertions, calculating it old and new way and asserting that obtained values are equal (tested on all `la` instances).
Note: using `!?` in PR title to indicate that changes introduce here **may** break the solver behaviour.
=> feat(jssp)!?: improve earliest finish time computation

examples/jssp/problem/fitness.rs
We do not need set capabilities for `delay_feasibles`. All we do is to iterate over the whole collection to find a maximum.
We could consider using binary heap here instead, but it might be done in next step.
=> perf(jssp): represent delay_feasibles as vec instead of hash set

examples/jssp/problem/fitness.rs
The code gets uglier but we avoid repeating few operations.
~Note: I'm not merging it yet as performance improvement is negligable.~
=> perf(jssp): compute highest priority operation alongside updating delay feasibles

examples/jssp/problem/fitness.rs
The only thing we need is number of currently scheduled operations -> we do not need to store operation ids.
This should redice allocations (memory footprint) & peformance (to the very very limited extent)
=> perf(jssp)?!: do not store scheduled operations

examples/jssp/problem/fitness.rs
I've used guarantee introduced in #444 
We do not need to iterate over all predecessors when checking whether all predecessors will have been finished in before `t_g + delay_g`. It is sufficient to check only the direct one, because it could have been scheduled only in case its own direct predecessor had finished (and so on...). However we need to handle special case of sink operation as it has every every operation in it's predecessor list. We do not need to handle operation zero, as it is always scheduled up front, before first call to this method ==> it is filtered out by previous predicate.
=> perf(jssp)!?: reduce complexity of `delay_feasibles` computation

examples/jssp/cli.rs, examples/jssp/config.rs, examples/jssp/main.rs, examples/jssp/problem/fitness.rs, examples/jssp/problem/replacement.rs, src/ga/timer.rs
- Add some important comments
- Parameterize delay_g calculation
=> feat(jssp): parameterize delay computation

src/ga.rs
Decided not to update `total_dur` before each hook call **for now**, to avoid vastly increasing number of syscalls.
This, however should be reconsidered in the future.
Added important comment to **slightly** decrease likelihood of future misuse of this field.
Closes #471
=> fix: add important comment and update `total_dur` just before `on_end` callback

coco/src/main.rs, src/ga.rs, src/ga/builder.rs, src/ga/builder/bitstring.rs, src/ga/builder/generic.rs, src/ga/builder/realvalued.rs, src/ga/operators/mutation.rs, src/ga/operators/mutation/impls.rs
Closes #477
Closes https://github.com/kkafar/master-monorepo/issues/246
=> refact: move `selection_rate` & `mutation_rate` out from `GAParams` to operators

coco/src/main.rs, examples/ga.rs, examples/jssp/main.rs, examples/jssp/problem/selection.rs, src/ga.rs, src/ga/builder/bitstring.rs, src/ga/builder/realvalued.rs, src/ga/operators/selection.rs, src/ga/operators/selection/impls.rs, src/ga/value_provider.rs, src/ga/value_provider/flat.rs, src/pso/particle.rs, src/pso/swarm.rs, tests/builder_tests.rs, tests/selection_tests.rs
- **Add ValueProvider trait**
- **Migrate RouletteWheel**
- **Migrate Random**
- **Migrate Rank**
- **Migrate RankR**
- **Migrate Tournament**
- **Migrate SUS**
- **Migrate Boltzmann**
- **Update docs**
- **Fix tests in selection impls module**
- **Fix leftovers**
Closes #193
=> feat!: allow for using adaptive values with operators by introducing ValueProvider trait
