ecrs-org/ecrs

- .gitignore
- src/ga.rs
- src/ga/example.rs
- src/ga/individual.rs
- src/ga/probe.rs
- src/ga/probe/csv_probe.rs
- src/ga/probe/json_probe.rs
- src/ga/probe/stdout_probe.rs
- src/main.rs
Adding alpha version of probes for genetic algorithm.
> feat: GA probes

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/missing-feature.md
- .github/PULL_REQUEST_TEMPLATE/pull-request.md
- .github/workflows/build-n-test.yaml
Added:
* simple PR template
* simple issue templates for bug report & missing features
Also fixed the CI, so it is only triggered when Rust codebase or it's configuration changes.
--
> chore: add issue & PR templates for bug report, missing feature

- src/examples.rs
- src/ga.rs
- src/ga/builder.rs
- src/ganew/individual.rs
- src/main.rs
This PR aims to overhaul current implementation of genetic algorithm. 
Major pain points in current implementation:
* It is not [pipeline](https://medium.com/@bonnotguillaume/software-architecture-the-pipeline-design-pattern-from-zero-to-hero-b5c43d8a4e60) oriented as it should be (idea coming from discussions with client). Besides that, current algorithm configuration style is not elegant.
* It lacks flexibility: currently only `f64` vectors are supported as chromosomes.
* Many more reasons... (TODO)
This PR added builder pattern for construction of GA instance. Pipeline & support for other chromosome representation in next PRs.
It partially deals with #21 but it does not introduce a pipeline as for now.
TODO
> feat: genetic algorithm overhaul

- src/ff.rs
Changed a few comments from polish to english
closes #11
> chore: purge polish

- src/ga.rs
- src/ga/builder.rs
Add time based search termination criteria. 
Resolves #60
> feat: add time based search termination criteria

- src/ga.rs
- src/ga/probe.rs
- src/ga/probe/stdout_probe.rs
So I restored logging on new best individual for GA algorithm (only Stdout probe) so it easier to work with. 
Logging for GA is still in TODO phase.
> chore: restore basic logging for GA

- src/ga/operators/crossover.rs
Basic documentation.
Resolves #96
> docs: `CrossoverOperator` trait

- src/ga/operators/crossover.rs
* Resolves #97 
* Resolves #98 
* Resolves #99 
* Resolves #100
> docs: crossover operators

- Cargo.lock
- Cargo.toml
> chore: update Cargo.toml

- example/src/ga.rs
- src/ga/probe/stdout_probe.rs
Life quality improvement
Resolves #141
> feat: add `new` method for `Stdout` probe

- src/ga/operators/crossover.rs
- src/ga/operators/mutation.rs
Add tests for mutation module.
This module has limited functionality yet. 
Resolves #102 
Resolves #101
> docs: mutation module

- src/ga/operators/mutation.rs
Added some very simple (mock) tests for `mutation` module
Resolves #144
> test: mock tests for `mutation` module

- src/ga/operators/selection.rs
- tests/selection_tests.rs
Added some basic tests for `selection` module.
Resolves #142
> test: `selection` module

- .github/workflows/build-test-example.yaml
- .github/workflows/build-test-lib.yaml
- src/aco.rs
- src/ga.rs
- src/ga/individual.rs
- src/ga/operators/selection.rs
- src/pso.rs
- tests/selection_tests.rs
Resolves #163 
Resolves #164
Resolves #162
> fix: selection operators

- example/src/ga.rs
- src/ga.rs
- src/ga/builder.rs
- tests/crossover_tests.rs
Added template type parameters for each of operators in GA => GA relies now on static dispatch only.
Resolves #125
> feat: move fully towards static dispatch in GA

- Cargo.lock
- example/Cargo.toml
- example/src/ga/rastrigin.rs
- example/src/main.rs
- src/ga.rs
- src/ga/probe.rs
- src/ga/probe/stdout_probe.rs
Fixed `StdoutProbe` && added logging backend to example application. 
Also I changed all `println!(…)` calls to `info!(…)` -- this allows end user to use any desired logging backend.
Resolves #126
> feat: improve probing for GA

- src/ga/operators/selection.rs
Resolves #106 
Resolves #107 
Resolves #105 
Resolves #108 
Resolves #103
> docs: `selection` module

- Cargo.toml
Added few fields to `Cargo.toml` that are required by `crates.io`.
> chore: prepare for release

- Cargo.toml
As title stays. See changes for details.
> fix: bad name of license field

- src/ga.rs
- src/ga/builder.rs
- src/ga/builder/presets.rs
- src/ga/operators/mutation.rs
- src/ga/probe/stdout_probe.rs
Add missing mutation operator
Resolves #49
> feat: add `flip` mutation operator

- src/ga/builder/presets.rs
- src/ga/operators/mutation.rs
> feat: `interchanging` mutation operator

- src/ga/operators/mutation.rs
Add missing operator
Resolves #51
> feat: reversing mutation operator

- example/src/aco.rs
- src/aco.rs
- src/aco/ant_system_cfg.rs
- src/aco/ants_system.rs
- src/aco/ants_system/builder.rs
> docs: improve docs in `aco` module

- src/ga.rs
- src/ga/probe.rs
- src/ga/probe/aggregated_probe.rs
- src/ga/probe/policy_driven_probe.rs
- src/ga/probe/probing_policy.rs
- src/ga/probe/stdout_probe.rs
Add missing documentation
Resolves #111 
Resolve #112
> docs: `probe` module

- Cargo.lock
- Cargo.toml
> release: 0.1.0-beta.0

- src/aco.rs
- src/aco/ant_system_cfg.rs
- src/aco/ants_system/builder.rs
- src/aco/ants_system/probe.rs
- src/aco/ants_system/probe/aggregated_probe.rs
- src/aco/ants_system/probe/csv_probe.rs
- src/aco/ants_system/probe/json_probe.rs
- src/aco/ants_system/probe/stdout_probe.rs
- src/aco/ants_system/solution.rs
> feat: improve ACO logging

- examples/aco_tsp.rs
- src/aco.rs
- src/aco/ants_system.rs
- src/aco/ants_system/builder.rs
- src/aco/ants_system/solution.rs
> fix: ACO bugs introduced with builder

- Cargo.toml
- benches/aco_bench.rs
- examples/aco_tsp.rs
- src/aco.rs
- src/aco/ant_system_cfg.rs
- src/aco/ants_system.rs
- src/aco/ants_system/builder.rs
- src/aco/pheromone.rs
- src/lib.rs
Resolves #226 and makes progress with #222
> feat: [ACO] extract feromon update operator

- src/aco/pheromone.rs
> feat: [ACO] Elitist ant system pheromone update

- src/aco/pheromone.rs
- src/aco/pheromone/best_policy.rs
> feat: [ACO] Max-Min  pheromone update

- src/aco/pheromone.rs
> feat: [ACO] Ant Colony System pheromone update

- src/ga/builder/bistring.rs
- src/ga/builder/realvalued.rs
- src/ga/population.rs
> feat: make population generators take RNG

- src/aco.rs
- src/aco/ant.rs
- src/aco/ants_system.rs
- src/aco/ants_system/builder.rs
Moves ant logic into Ant struct. It will allow for local pheromone update
Resolves #238 
It creates an 7% drop in performance #225
> feat: Extract ant struct

- README.md
- src/ga/individual.rs
Added missing docs for `ga::individual` module && removed version note from readme.
Resolves #254
Resolves #114
> docs: `individual` module & small readme update

- benches/aco_bench.rs
- examples/aco_tsp_logging.rs
- src/aco/probe.rs
- src/aco/probe/aggregated_probe.rs
- src/aco/probe/csv_probe.rs
- src/aco/probe/json_probe.rs
- src/aco/probe/policy_driven_probe.rs
- src/aco/probe/probing_policy.rs
- src/aco/probe/stdout_probe.rs
> feat: ProbingPolicy for ACO

- src/aco.rs
- src/aco/ants_behaviour.rs
- src/aco/builder.rs
- src/aco/fitness.rs
- src/aco/pheromone.rs
- src/aco/pheromone/best_policy.rs
- src/aco/solution.rs
Resolves #241 
#225 makes program run ~12% faster
#257 remove matrix from cost calculations
> feat: Allow for custom solution grading in ACO

- benches/aco_bench.rs
- examples/aco_ant_system_tsp.rs
- examples/aco_max_min_ant_system_tsp.rs
- examples/aco_tsp.rs
- examples/aco_tsp_logging.rs
- src/aco.rs
- src/aco/aco_cfg.rs
- src/aco/ant.rs
- src/aco/ants_behaviour.rs
- src/aco/builder.rs
- src/aco/fitness.rs
- src/aco/goodness.rs
- src/aco/pheromone.rs
> feat: Improve ACO builder

- examples/ga.rs
- src/ga/operators/replacement.rs
Add `WeakParent` replacement operator impl.
Resolves #57 
--
> feat: `replacement` - `WeakParent`

- src/aco.rs
- src/aco/ant.rs
- src/aco/ants_behaviour.rs
- src/aco/builder.rs
> feat: Exploiting ant

- src/ga/operators/replacement.rs
- tests/replacement_tests.rs
Add some tests for `replacement` module
Resolves #272 
--
> tests: `replacement` module

- src/ga/operators/replacement.rs
> fix: `WeakParent` does invalid swaps

- examples/pso_multiple_probes.rs
- src/pso.rs
- src/pso/probe/aggregated_probe.rs
> refact: 'add_probe' method for AggregatedProbe for PSO

- benches/aco_bench.rs
- examples/aco_ant_colony_system_tsp.rs
- examples/aco_ant_system_tsp.rs
- examples/aco_max_min_ant_system_tsp.rs
- examples/aco_tsp_logging.rs
- examples/aco_with_local_update.rs
- src/aco.rs
- src/aco/builder.rs
- src/aco/probe.rs
- src/aco/probe/aggregated_probe.rs
- src/aco/probe/csv_probe.rs
- src/aco/probe/json_probe.rs
- src/aco/probe/policy_driven_probe.rs
- src/aco/probe/probing_policy.rs
- src/aco/probe/stdout_probe.rs
- src/aco/termination_condition.rs
> feat: Termination condition for ants algorithm

- src/aco.rs
- src/aco/pheromone.rs
- src/aco/pheromone/best_policy.rs
- src/aco/probe/csv_probe.rs
- src/aco/probe/stdout_probe.rs
- src/aco/solution.rs
Code clean-up
#225 +10% in performance
> chore: Minor ant colony module clean-up 

- examples/pso_multiple_probes.rs
- src/pso/particle.rs
- src/pso/swarm.rs
> refact: random distribution in PSO

- src/ff.rs
Parallelization of firefly comparison utilizing rayon's implementation of thread pool.
Resolves #293
> [FF] Parallelization of population iterations

- src/ff/probe/csv_probe.rs
- src/ff/probe/stdout_probe.rs
Logs position of best solution in csv/stdout
Resolves #300
> Fix: [ff] best solution's postion not passed to csv/stdout

- src/ff.rs
Implements random motion for the brightest firefly in a generation, with random movement scaling with alpha parameter.
Resolves #302
> [FF] Implementation of brownian motion for currently brightest firefly

- Cargo.toml
- benches/ff_bench.rs
- src/ff.rs
- src/ff/probe.rs
- src/ff/probe/empty_probe.rs
- src/ff/probe/stdout_probe.rs
Implementation of criterion-based benchamrk for FF with 3 targets: 1/4, 1/2 and full.
Resolves #304 
Does not yet implement preset fireflies population.
> Ff criterion benchmark

- src/test_functions/mod.rs
Implementation of additional test functions
Resolves #310
> Additional test functions

- .github/workflows/build-test-coco.yaml
- Cargo.toml
- coco/.gitignore
- coco/Cargo.toml
- coco/README.md
- coco/src/adapter.rs
- coco/src/main.rs
- src/ga.rs
- src/ga/operators/fitness.rs
For this moment integration exists only for genetic algorithm and is restricted to single objective optimization with no constraints.
Resolves #22
> feat: `COCO` integration

- src/ff.rs
- src/ff/builder.rs
Implementation of "builder" pattern for firefly algorithm.
Resolves #317
> feat: `builder` for firefly algorithm

- src/ff.rs
- src/ff/population.rs
Refactored fireflies population to a separate struct
This is just an implementation of said struct, it is not actually implemented in the algorithm itself.
> refactor: Fireflies' population

- examples/ff_logging.rs
- src/ff.rs
- src/ff/builder.rs
- src/ff/population.rs
Refactorization of fireflies algorithm to utilize the population struct.
Resolves #319 
As population is a wrapped Vec, I didn't implement an Iterator, but the set of traits that stock vectors use to allow iteration.
> refactor: `population` in firefly algorithm

- src/test_functions/mod.rs
Most of them were found in "A Literature Survey of Benchmark Functions For Global
Optimization Problems", Jamil, Yang et al.
> chore: even more test functions

- src/test_functions/mod.rs
Addition of more test fuctions, this time sorted alphabetically.
> chore: additional test functions

- coco/src/adapter.rs
- coco/src/main.rs
- src/ga/population.rs
> feat: improve `COCO` integration

- coco/src/adapter.rs
- coco/src/main.rs
- src/ga.rs
- src/ga/population.rs
> refact: `COCO` integration cleanup

- Cargo.toml
> release: 0.1.0-beta.3

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/missing-feature.md
Fixed typos in `Bug report` & `Missing feature` issue templates.
> chore: fix typos in issue templates

- src/ga/operators/mutation.rs
Add `inversion` mutation operator. 
Implementation was taken from text of our thesis.
> feat: `inversion` mutation operator

- src/ga.rs
Making template type parameters more verbose, so that the code is possible to work with especially after a break.
> refact: make template type params more verbose

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/PULL_REQUEST_TEMPLATE.md
Fix few typos in bug report & PR template
> chore: fix typos in templates

- .rustfmt.toml
- examples/jssp.rs
- src/ga/individual.rs
- src/ga/operators/replacement.rs
- src/ga/population.rs
Add operators & example for Jop Shop Scheduling Problem
Also updated rustfmt configuration & added some useful operators.
> feat: add operators & example for JSSP

- examples/ga.rs
- examples/ga_ackley_test_function.rs
- examples/ga_bsc.rs
- examples/ga_rvc.rs
- examples/jssp/main.rs
- examples/jssp/problem.rs
- examples/jssp/problem/individual.rs
- examples/jssp/problem/state.rs
- examples/jssp/util.rs
- src/pso/probe/stdout_probe.rs
> chore: apply clippy fixes across codebase

- examples/jssp/main.rs
- examples/jssp/problem/individual.rs
There was no update to `delay` value when `g` changed in inner loop
> fix: `delay` was not updated in inner loop

- examples/jssp/main.rs
- examples/jssp/problem.rs
- examples/jssp/problem/individual.rs
- examples/jssp/problem/state.rs
- Fix indexing, delay update, g update
- Add elitism
- Derive Clone trait  for model structs
> feat: add elitisim in jssp & cleanup

- Cargo.toml
- examples/jssp/cli.rs
- examples/jssp/logging.rs
- examples/jssp/main.rs
- examples/jssp/parse.rs
- examples/jssp/problem.rs
Allow for loading JSSP instances from external data files
Resolves #354
> feat: allow for loading external jssp instances

- .githooks/pre-commit
- .githooks/pre-push
- .github/workflows/build-test-coco.yaml
- .github/workflows/build-test-example.yaml
- .github/workflows/build-test-lib.yaml
- .github/workflows/clippy-check.yaml
- .github/workflows/fmt-check.yaml
- Cargo.toml
- README.md
- coco/src/main.rs
- examples/jssp/cli.rs
- examples/jssp/main.rs
- examples/jssp/parse.rs
- examples/jssp/problem.rs
- examples/jssp/problem/individual.rs
- src/ga.rs
- src/lib.rs
- src/prelude.rs
- src/pso.rs
- src/test_functions/mod.rs
- tests/builder_tests.rs
- tests/crossover_tests.rs
- tests/replacement_tests.rs
- tests/selection_tests.rs
Forgetting about applying clippy & fmt is annoying -- never more
> chore: setup hooks & hide more functionalities behind features

- Cargo.toml
- src/ga/builder.rs
- src/ga/builder/bitstring.rs
- src/ga/builder/generic.rs
- src/ga/builder/realvalued.rs
- src/ga/individual.rs
- src/ga/operators/fitness.rs
- src/ga/operators/selection.rs
- Add dependency on num-traits
- Generalise fitness
Resolves #133
Resolves #360
> feat: allow for custom fitness types

- examples/jssp/problem/crossover.rs
- examples/jssp/problem/individual.rs
- src/ga.rs
> perf: evaluate fitness only when necessary

- examples/jssp/main.rs
- examples/jssp/problem.rs
- examples/jssp/problem/population.rs
- src/ga/builder.rs
- src/ga/operators/mutation.rs
- tests/selection_tests.rs
> fix: fixed machine size

- Cargo.toml
- examples/jssp/logging.rs
- examples/jssp/problem.rs
- examples/jssp/problem/individual.rs
This is a miscellaneous PR -- didn't want to split it up into 10 one-liners -- all these changes were required to make the local search work properly.
Most important changes:
1. Refactored out (and fixed series of bugs!) operation swapping code (local search) so there is only single point of failure now (regarding & updating operation state for dfs)
2. Ensured that there are debug symbols in debug build.
3. Ensured that machines & operations state is correctly reset when required.
4. Fixed a bug in dfs implementation when vertices with no feasible edges were not popped from the stack (infinite loop).
Resolves #387
> fix: series of bugs in localsearch & many other small bugs

- .github/workflows/build-test-coco.yaml
- .github/workflows/build-test-example.yaml
- .github/workflows/build-test-lib.yaml
- .github/workflows/clippy-check.yaml
- .github/workflows/fmt-check.yaml
Added concurrency groups for all CI workflows.
Closes #393
> chore(ci): add concurrency groups for all CI workflows

- Cargo.toml
> release: 0.1.0-beta.4

- examples/jssp/main.rs
- examples/jssp/problem.rs
- examples/jssp/problem/replacement.rs
- src/ga/operators/replacement.rs
- tests/replacement_tests.rs
Implemented custom (as ECRS needs still some refactoring to enable elitism & random sampling) replacement operator for JSSP.
Closes #381
Closes #380
> feat(jssp): add custom replacement operator

- examples/jssp/cli.rs
- examples/jssp/main.rs
- examples/jssp/parse.rs
- examples/jssp/problem/population.rs
- Improve CLI validation
- Require input & output file to be provided
- Prepend unused arguments with underscores
- Fix cli validation
> chore(jssp): improve CLI & align it to ECDataKit

- examples/jssp/problem/probe.rs
- src/ga.rs
- src/ga/probe.rs
- src/ga/probe/aggregated_probe.rs
- src/ga/probe/policy_driven_probe.rs
- src/ga/probe/probing_policy.rs
- src/ga/timer.rs
- Add super simple timer type
- Log duration of particular operators
> feat(jssp): log duration of particular operators

- examples/jssp/problem/probe.rs
- src/ga.rs
- src/ga/probe/probing_policy.rs
- src/ga/probe/stdout_probe.rs
> refact: shorter names for fields in GAMetadata

- examples/jssp/cli.rs
Changes done in sync with ec datakit
Closes #420
> feat(jssp): strip not necessary cli parameters

- examples/jssp/parse.rs
- examples/jssp/problem.rs
- examples/jssp/problem/individual.rs
- examples/jssp/problem/population.rs
- Inline calls in IndividualTrait impl for JsspIndividual
- Comments in individual & machine impl
- Use Option for operation finish time
- Add comments to Edge, EdgeKind & Operation
- Extend comments on Operation
- Add more comments in problem module
- Comments in population module
> chore(jssp): mostly document structures used to model JSSP

- examples/jssp/logging.rs
- examples/jssp/main.rs
- examples/jssp/problem/population.rs
- examples/jssp/problem/probe.rs
- examples/jssp/util.rs
- Improve op printing in main
- Fix typo:
- Format & clippy fixes
- Fix invalid operation intialization
> fix(jssp): invalid value passed as duration to zero & sink ops

- Cargo.toml
- examples/jssp/logging.rs
- examples/jssp/main.rs
- examples/jssp/problem/probe.rs
> feat(jssp): print solution order, hash & more metadata at solution end

- .github/workflows/run-jssp-solver.yaml
Adding CI to ensure that the program does not crash even on mock data as it did couple of commits ago
> feat(CI): run JSSP example on CI

- examples/jssp/logging.rs
- examples/jssp/problem/probe.rs
- Pretty print json output
- Print chromosome
> feat(jssp): print chromosome & pretty format the json

- examples/jssp/problem/probe.rs
> fix(jssp): iterinfo event csv file had invalid schema

- examples/jssp/problem/probe.rs
> fix(jssp): more precise, but VERY SLOW, diversity estimation

- examples/jssp/problem/probe.rs
> fix(jssp): format code to fix CI

- examples/jssp/problem/individual.rs
- Redundant namespaces
- Use turbo fish to make type explicit
- Add comment on g
- Add comments on delay_fesibles
- More comments
- Comments on g, t_g
- Typos
- More cleanup
> chore: comments & cleanup before optimising

- examples/jssp/problem/fitness.rs
This vastly reduces memory allocs
> feat(jssp): hoist state from evalutaion func to the struct

- examples/jssp/problem/fitness.rs
- examples/jssp/problem/individual.rs
> fix(jssp,CI): fmt & clippy

- examples/jssp/problem/fitness.rs
This will allow for parameterization
> refact(jssp): extract delay_g computation to spearate function

- examples/jssp/main.rs
- examples/jssp/problem/fitness.rs
- Clippy
- Disable max duration stop condition
> chore(jssp): disable max duration stop condition

- scripts/build-jssp-on-ares.sh
- Add script for building jssp binary on Ares
- Add minimal logging to building script
- Add sbatch configuration
> feat: working setup for ares

- examples/jssp/cli.rs
- examples/jssp/config.rs
- examples/jssp/main.rs
> feat(jssp): allow for loading parameters from json config file

- Cargo.toml
> chore: allow for more aggresive optimization in build options

- examples/jssp/problem.rs
- examples/jssp/problem/fitness.rs
> fix(jssp): use right-side open range for Machine#is_idle query

- examples/jssp/problem.rs
- examples/jssp/problem/fitness.rs
- examples/jssp/problem/probe.rs
- Add important comment on possible bug
- Add some important comment on edges_out field
- Whitespace
- Add some important comments
- Fix crucial issues with hash computing...
- More comments
> fix(jssp): op sorting for has computing & important comments

- examples/jssp/problem/fitness.rs
- examples/jssp/problem/probe.rs
- examples/jssp/util.rs
- Remove comment
- Exchange diversity for euclidean distance metric
> feat: exchange diversity for popmetrics (including avg. eucl. distance)

- examples/jssp/util.rs
> fix(jssp): typo in event data file name

- examples/jssp/cli.rs
- examples/jssp/config.rs
- examples/jssp/main.rs
- examples/jssp/problem.rs
- examples/jssp/problem/crossover.rs
- examples/jssp/problem/replacement.rs
- examples/jssp/problem/selection.rs
- Prepare randomsearch solver
- Allow for setting wheterh to use random search in config file
> feat(jssp): add solver based on randomsearch

- examples/jssp/config.rs
- examples/jssp/main.rs
- examples/jssp/problem/crossover.rs
- examples/jssp/problem/replacement.rs
- examples/jssp/util.rs
> feat(jssp): log on entering solver function

- examples/jssp/problem/individual.rs
- src/ga/individual.rs
- src/ga/operators/crossover.rs
Added `FixedPoint` crossover operator
Resolves kkafar/master-monorepo#110
> feat: add `FixedPoint` crossover

- src/ga/builder.rs
> fix: building after feature mismatch

- src/ga/operators/selection.rs
- src/ga/operators/selection/impls.rs
> feat!: fix `Random` & add `UniqueRandom`
